<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMessagesWithSomeone($myId, $otherUserId, $list = 0)
    {

        $dql = 'SELECT m FROM AppBundle:Message m WHERE (m.acceptUser = :myId OR m.acceptUser = :otherUserId) AND 
        (m.sendUser = :myId OR m.sendUser = :otherUserId) ORDER BY m.dateAdded DESC';

        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('myId', $myId)
            ->setParameter('otherUserId', $otherUserId)
            ->setFirstResult($list)
            ->setMaxResults(21);

        return $query->getResult();
    }
}
