acme_rpc:
  channel: sample/{method}
  handler:
    callback: 'acme.rpc' #related to the getName() or your RPC service
  requirements:
    method:
      pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !

acme_topic:
  channel: acme/channel
  handler:
    callback: 'acme.topic'

